app:
  log_level: info
  log_type: text
  api_addr: "127.0.0.1:8080"

socks5:
  listen_addr: "127.0.0.1:1085"
  username: ""
  password: ""

workers:
  - id: "ssh-sg-1"
    type: "ssh"
    host: "biznet.vpnstore28.my.id"
    port: 443
    username: "hehe"
    password: "hehe"
    private_key: ""
    payload_name: ""
    remote_proxy: "104.21.83.135:80"
    remote_proxy_mode: "ws"
    remote_proxy_path: "/"
    remote_proxy_tls: false
    connect_timeout: "15s"
    keepalive_sec: 30

outbounds:
  - name: "pool-sg"
    type: "pool"
    worker_ids: ["ssh-sg-1"]
    strategy: "least_conn"
  - name: "direct"
    type: "direct"

rules:
  - type: "domain_suffix"
    value: "vidio.com"
    outbound: "pool-sg"
  - type: "domain_keyword"
    value: "netflix"
    outbound: "pool-sg"
  - type: "cidr"
    value: "10.0.0.0/8"
    outbound: "direct"
  - type: "match"
    value: ""
    outbound: "direct"

domains: []

payloads:
  - name: "ws-vidio"
    data: "GET / HTTP/1.1[crlf]Host: edu.ruangguru.com[crlf]Connection: Keep-Alive[crlf][crlf][split]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 69[crlf][crlf]"