app:
  log_level: info
  log_type: text
  api_addr: "127.0.0.1:8080"

socks5:
  listen_addr: "127.0.0.1:1080"
  username: ""
  password: ""

workers:
  - id: "ssh-sg-1"
    type: "ssh"
    host: "sg1.example.com"
    port: 22
    username: "root"
    password: "secret"
    private_key: ""
    payload_name: ""
    connect_timeout: "10s"
    keepalive_sec: 30

outbounds:
  - name: "pool-sg"
    type: "pool"
    worker_ids: ["ssh-sg-1"]
    strategy: "least_conn"
  - name: "direct"
    type: "direct"

rules:
  - type: "domain_suffix"
    value: "vidio.com"
    outbound: "pool-sg"
  - type: "domain_keyword"
    value: "netflix"
    outbound: "pool-sg"
  - type: "cidr"
    value: "10.0.0.0/8"
    outbound: "direct"
  - type: "match"
    value: ""
    outbound: "direct"

domains:
  - name: "pool-sg"
    file_path: "lists/sg.txt"

payloads:
  - name: "default"
    data: "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Keep-Alive[crlf][crlf][split]HTTP/1.1 200 OK[crlf]"

